### ISSUE TITLE
Update all READMEs for embassy-os v0.3.0

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/community-services#11]
- [ ] bitcoind
- [ ] btc-rpc-proxy
- [ ] btcpayserver
- [ ] burn-after-reading
- [ ] c-lightning
- [ ] cups
- [ ] embassy-pages
- [ ] filebrowser
- [ ] hello-world
- [ ] lnd
- [ ] mastodon
- [ ] photoview
- [ ] ride-the-lightning
- [ ] spark-wallet
- [ ] sphinx-relay
- [ ] synapse
- [ ] thunderhub
- [ ] vaultwarden

**Comment by MattDHill** [comment]
Still valid?

**Comment by chrisguida** [comment]
Not sure, it's not valid for all services I've worked on recently, but I'll keep an eye out
