### ISSUE TITLE
Evaluate Services for essential pointer volume behavior

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/community-services#5]
- [x] sphinx
- [x] btcpay
- [x] embassy pages
- [x] spark
- [x] thunderhub
- [x] photoview
- [x] ride-the-lightning

If any of these services essentially cannot function without its pointer volume data it should check for the existence of that pointer volume being mounted on startup. If it does not exist, the service should exit with a ZERO exit code. This will put it into a crash loop while it waits for the transient lack of pointer volumes to be remedied.

**Comment by ProofOfKeags** [comment]
For additional context see embassy-os#1026 and embassy-os#1073

**Comment by elvece** [comment]
For UAT:

- [ ] sphinx
- [ ] btcpay
- [ ] embassy pages
- [ ] spark
- [ ] thunderhub
- [ ] photoview
- [ ] ride-the-lightning
