### ISSUE TITLE
Cut release tags for all 0.3.0 services

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/community-services#7]
- [x] [bitcoind](https://github.com/Start9Labs/bitcoind-wrapper)
- [x] [btc-rpc-proxy](https://github.com/Start9Labs/btc-rpc-proxy-wrapper)
- [x] [btcpayserver](https://github.com/Start9Labs/btcpayserver-wrapper)
- [x] [burn-after-reading](https://github.com/Start9Labs/burn-after-reading)
- [x] [c-lightning](https://github.com/Start9Labs/c-lightning-wrapper)
- [x] [cups](https://github.com/Start9Labs/cups-wrapper)
- [x] [embassy-pages](https://github.com/Start9Labs/embassy-pages-wrapper)
- [x] [filebrowser](https://github.com/Start9Labs/filebrowser-wrapper)
- [x] [hello-world](https://github.com/Start9Labs/hello-world-wrapper)
- [x] [lnd](https://github.com/Start9Labs/lnd-wrapper)
- [x] [mastodon](https://github.com/Start9Labs/mastodon-wrapper)
- [x] [photoview](https://github.com/Start9Labs/embassyos-photoview-wrapper)
- [x] [ride-the-lightning](https://github.com/Start9Labs/ride-the-lightning-wrapper)
- [x] [spark-wallet](https://github.com/Start9Labs/spark-wallet-wrapper)
- [x] [sphinx-relay](https://github.com/Start9Labs/sphinx-relay-wrapper)
- [x] [synapse](https://github.com/Start9Labs/synapse-wrapper)
- [x] [thunderhub](https://github.com/Start9Labs/thunderhub-wrapper)
- [x] [vaultwarden](https://github.com/Start9Labs/vaultwarden-wrapper)

**Comment by elvece** [comment]
Checkboxes reflect draft releases that have been created for each service.
Preliminary release notes added - determine if more necessary.
This ticket can be closed when releases are officially published.

**Comment by chrisguida** [comment]
Will still need to upload S9PKs and create release tags

**Comment by ProofOfKeags** [comment]
There have been commits to master on a few services since the draft tags were cut.

**Comment by elvece** [comment]
@chrisguida the release target is set as master

**Comment by chrisguida** [comment]
Cool, that's what I thought, thanks

**Comment by chrisguida** [comment]
TODO:

1. Cut release tag
2. Build
3. Push to alpha/beta reg
4. Push to prod reg
