### ISSUE TITLE
Ensure all health checks show starting/loading states on startup

### ISSUE THREAD

**Issue by elvece** [Start9Labs/community-services#8]
Make "starting" and "loading" states for all service health checks, mainly those that are currently implemented as just simple `curl` commands.

- [x] bitcoind
- [x] btc-rpc-proxy
- [x] btcpayserver
- [x] burn-after-reading
- [x] c-lightning
- [x] cups
- [x] embassy-pages
- [x] filebrowser
- [x] hello-world
- [x] lnd
- [x] mastodon
- [x] photoview
- [x] ride-the-lightning
- [x] spark-wallet
- [x] sphinx-relay
- [x] synapse
- [x] thunderhub
- [x] vaultwarden

Edit: Note: must use `io-format: json` in order to parse duration easily from stdin. Also the RTL solution requires `bash`.

**Comment by chrisguida** [comment]
Waiting for [this issue](https://github.com/Start9Labs/ride-the-lightning-wrapper/issues/12) to be solved before replicating the solution a bunch of times

**Comment by chrisguida** [comment]
Loading phase for C-Lightning: https://github.com/Start9Labs/c-lightning-wrapper/issues/30

**Comment by elvece** [comment]
Testing complete, closing.
